"""Core-service #8 — the template → PDF engine, in isolation.

Every test here injects a fake renderer. That is not merely convenient: it is
what lets the suite run on a host without Pango, and it keeps these tests about
the ENGINE (registry lookup, context hashing, escaping, failure handling) rather
than about WeasyPrint's output. One test exercises the real renderer and is
skipped when the native stack is absent.
"""

from __future__ import annotations

import pytest

from office_connect.core.documents import (
    DocumentSpec,
    RenderFailed,
    UnknownDocument,
    build_stylesheet,
    fingerprint_context,
    register_document,
    register_template_dir,
    render_document,
)
from office_connect.core.documents import templates as doc_templates
from office_connect.core.ui.tokens import NEUTRAL_TOKENS

pytestmark = pytest.mark.filterwarnings("ignore::DeprecationWarning")


class _FakeRenderer:
    """Records what it was handed and returns something PDF-shaped."""

    name = "fake"

    def __init__(self, payload: bytes = b"%PDF-1.7 fake") -> None:
        self.payload = payload
        self.html: str | None = None
        self.stylesheet: str | None = None

    def render(self, html: str, *, stylesheet: str) -> bytes:
        self.html = html
        self.stylesheet = stylesheet
        return self.payload


@pytest.fixture
def sample_template(tmp_path):
    """A registered document whose template lives in a temp directory."""
    (tmp_path / "sample.html.j2").write_text(
        "<h1>{{ doc.title }}</h1><p>{{ payee }}</p><p>{{ amount | money }}</p>",
        encoding="utf-8",
    )
    register_template_dir(tmp_path)
    # A new directory must be visible to the cached environment.
    doc_templates.get_environment(refresh=True)
    return register_document(
        DocumentSpec(key="test.sample", template="sample.html.j2", title="Sample Form")
    )


def _context(**overrides):
    base = {
        "doc": {"title": "Sample Form"},
        "payee": "Juan Dela Cruz",
        "amount": "6500.00",
    }
    base.update(overrides)
    return base


async def test_renders_a_registered_document_and_hashes_both_sides(sample_template):
    renderer = _FakeRenderer()
    result = render_document(
        key="test.sample", context=_context(), renderer=renderer
    )

    assert result.key == "test.sample"
    assert result.title == "Sample Form"
    assert result.pdf.startswith(b"%PDF-")
    # Two hashes answering two questions: bytes (tamper) and inputs (change).
    assert len(result.content_sha256) == 64
    assert len(result.source_fingerprint) == 64
    assert result.content_sha256 != result.source_fingerprint
    assert "Juan Dela Cruz" in result.html


async def test_money_filter_formats_but_never_computes(sample_template):
    renderer = _FakeRenderer()
    result = render_document(
        key="test.sample",
        context=_context(amount="6500.00"),
        renderer=renderer,
    )
    # The server's 2-dp string, formatted for print. The template has no way to
    # add, net or round — the filter takes a string and returns a string.
    assert "₱6,500.00" in result.html


async def test_user_text_is_escaped_into_the_document(sample_template):
    """A purpose field is user input; a generated PDF must not carry its markup.

    This is also what justifies storing generated bytes without a virus scan:
    the renderer's input is fully escaped, so its output is fully ours.
    """
    result = render_document(
        key="test.sample",
        context=_context(payee="<script>alert(1)</script>"),
        renderer=_FakeRenderer(),
    )
    assert "<script>" not in result.html
    assert "&lt;script&gt;" in result.html


async def test_a_missing_context_key_fails_loudly(sample_template):
    """StrictUndefined: a blank amount on a voucher is worse than no voucher."""
    with pytest.raises(RenderFailed):
        render_document(
            key="test.sample",
            context={"doc": {"title": "Sample Form"}, "payee": "X"},  # no amount
            renderer=_FakeRenderer(),
        )


async def test_non_pdf_output_is_refused(sample_template):
    """A renderer that returns junk must not reach the attachment store.

    Storing it would flip a checklist item to Generated with nothing behind it —
    the one failure mode that silently lies to an approver.
    """
    with pytest.raises(RenderFailed):
        render_document(
            key="test.sample",
            context=_context(),
            renderer=_FakeRenderer(payload=b"<html>not a pdf</html>"),
        )
    with pytest.raises(RenderFailed):
        render_document(
            key="test.sample", context=_context(), renderer=_FakeRenderer(payload=b"")
        )


async def test_unknown_key_raises_before_any_work():
    with pytest.raises(UnknownDocument):
        render_document(key="nope.missing", context={}, renderer=_FakeRenderer())


async def test_fingerprint_is_stable_across_key_order():
    """The idempotence check depends on this: two equal contexts, one hash."""
    a = fingerprint_context({"x": 1, "y": {"b": 2, "a": 3}})
    b = fingerprint_context({"y": {"a": 3, "b": 2}, "x": 1})
    assert a == b
    assert a != fingerprint_context({"x": 1, "y": {"a": 3, "b": 4}})


async def test_stylesheet_is_built_from_design_tokens():
    """Standing rule 1 does not stop at the screen."""
    css = build_stylesheet(None)
    assert f"--oc-color-brand: {NEUTRAL_TOKENS['color']['brand']};" in css
    assert "--oc-status-warn:" in css
    # Page geometry is print-only and legitimately not a token.
    assert "size: A4 portrait" in css
    # The font family names what the image actually installs; `system-ui` would
    # resolve to nothing in the container and render blank boxes.
    assert "DejaVu Sans" in css


async def test_tenant_branding_reaches_the_print_stylesheet():
    css = build_stylesheet({"tokens": {"color": {"brand": "#123456"}}})
    assert "--oc-color-brand: #123456;" in css


async def test_the_stylesheet_the_renderer_receives_is_the_built_one(sample_template):
    renderer = _FakeRenderer()
    render_document(
        key="test.sample",
        context=_context(),
        branding={"tokens": {"color": {"brand": "#abcdef"}}},
        renderer=renderer,
    )
    assert renderer.stylesheet is not None
    assert "--oc-color-brand: #abcdef;" in renderer.stylesheet


async def test_real_weasyprint_produces_a_pdf(sample_template):
    """The one test that exercises the production renderer.

    Skipped where the Pango stack is absent (a Windows dev host); it runs in the
    container, which is the only place WeasyPrint is ever allowed to run.
    """
    pytest.importorskip("weasyprint")
    result = render_document(key="test.sample", context=_context())
    assert result.pdf.startswith(b"%PDF-")
    assert len(result.pdf) > 1000
