"""reimbursement schema + reference numbers

Revision ID: 0013
Revises: 0012
Create Date: 2026-07-27

Stage C Increment R-1 — the Local Travel Reimbursement schema + config pack, plus the
core reference-number service (#5). Drafted with `alembic revision --autogenerate` from
the models, then hand-tuned for: append-only `REVOKE UPDATE` (reimb_return_events /
reimb_status_histories / reimb_external_events) and enum-type drops on downgrade
(autogenerate omits both). `reimb_claims.workflow_instance_id` FKs INTO the Stage-C
workflow engine (module → core). Reversible (down→up) + idempotent.

Deferred vs build spec §5: reimb_approval_steps (superseded by core_workflow_steps),
reimb_signatory_configs (the workflow definition, R-4-app), reimb_template_maps (R-5).
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "0013"
down_revision: Union[str, None] = "0012"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Native enums created inline by the first create_table that uses each (each enum is
# used by exactly one table). Listed here so downgrade can drop the TYPES.
_REIMB_ENUMS: tuple[str, ...] = (
    "reimb_claim_kind",
    "reimb_fund_source",
    "reimb_holder_kind",
    "reimb_transport_mode",
    "reimb_checklist_group",
    "reimb_checklist_evidence",
    "reimb_checklist_item_status",
    "reimb_cash_advance_status",
    "reimb_return_reason_category",
    "reimb_return_target",
    "reimb_attachment_custody",
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('core_reference_sequences',
    sa.Column('scope', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('last_value', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['core_users.id'], name=op.f('fk_core_reference_sequences_created_by_core_users')),
    sa.ForeignKeyConstraint(['deleted_by'], ['core_users.id'], name=op.f('fk_core_reference_sequences_deleted_by_core_users')),
    sa.ForeignKeyConstraint(['updated_by'], ['core_users.id'], name=op.f('fk_core_reference_sequences_updated_by_core_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_core_reference_sequences'))
    )
    op.create_index('uq_core_reference_sequences_scope_year', 'core_reference_sequences', ['scope', 'year'], unique=True)
    op.create_table('reimb_cash_advances',
    sa.Column('claimant_id', sa.BigInteger(), nullable=False),
    sa.Column('dv_no', sa.String(), nullable=True),
    sa.Column('dv_date', sa.Date(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('dpo_no', sa.String(), nullable=True),
    sa.Column('date_return', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('open', 'liquidation_started', 'settled', 'overdue', name='reimb_cash_advance_status'), server_default='open', nullable=False),
    sa.Column('settled_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['claimant_id'], ['core_staff.id'], name=op.f('fk_reimb_cash_advances_claimant_id_core_staff')),
    sa.ForeignKeyConstraint(['created_by'], ['core_users.id'], name=op.f('fk_reimb_cash_advances_created_by_core_users')),
    sa.ForeignKeyConstraint(['deleted_by'], ['core_users.id'], name=op.f('fk_reimb_cash_advances_deleted_by_core_users')),
    sa.ForeignKeyConstraint(['updated_by'], ['core_users.id'], name=op.f('fk_reimb_cash_advances_updated_by_core_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reimb_cash_advances'))
    )
    op.create_index('ix_reimb_cash_advances_claimant_id', 'reimb_cash_advances', ['claimant_id'], unique=False)
    op.create_index('ix_reimb_cash_advances_date_return', 'reimb_cash_advances', ['date_return'], unique=False)
    op.create_index('ix_reimb_cash_advances_status', 'reimb_cash_advances', ['status'], unique=False)
    op.create_index('uq_reimb_cash_advances_open_per_claimant', 'reimb_cash_advances', ['claimant_id'], unique=True, postgresql_where=sa.text("status IN ('open', 'liquidation_started', 'overdue') AND deleted_at IS NULL"))
    op.create_table('reimb_checklist_catalogs',
    sa.Column('claim_kind', sa.String(), nullable=True),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('group', sa.Enum('authority', 'itinerary', 'proof_of_travel', 'transport', 'lodging_meals', 'report', 'financial', name='reimb_checklist_group'), nullable=False),
    sa.Column('required_rule', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('auto_checks', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('evidence', sa.Enum('upload', 'generated_doc', 'external_wet_sign', 'data_only', name='reimb_checklist_evidence'), nullable=False),
    sa.Column('circular_version', sa.String(), nullable=True),
    sa.Column('sort', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.BigInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['core_users.id'], name=op.f('fk_reimb_checklist_catalogs_created_by_core_users')),
    sa.ForeignKeyConstraint(['deleted_by'], ['core_users.id'], name=op.f('fk_reimb_checklist_catalogs_deleted_by_core_users')),
    sa.ForeignKeyConstraint(['updated_by'], ['core_users.id'], name=op.f('fk_reimb_checklist_catalogs_updated_by_core_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reimb_checklist_catalogs'))
    )
    op.create_index('ix_reimb_checklist_catalogs_group', 'reimb_checklist_catalogs', ['group'], unique=False)
    op.create_index('uq_reimb_checklist_catalogs_kind_code', 'reimb_checklist_catalogs', ['claim_kind', 'code'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('reimb_configs',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('value_display', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.BigInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['core_users.id'], name=op.f('fk_reimb_configs_created_by_core_users')),
    sa.ForeignKeyConstraint(['deleted_by'], ['core_users.id'], name=op.f('fk_reimb_configs_deleted_by_core_users')),
    sa.ForeignKeyConstraint(['updated_by'], ['core_users.id'], name=op.f('fk_reimb_configs_updated_by_core_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reimb_configs'))
    )
    op.create_index('ix_reimb_configs_key', 'reimb_configs', ['key'], unique=False)
    op.create_index('uq_reimb_configs_key_scope', 'reimb_configs', ['key', 'effective_from', 'tenant_id'], unique=True, postgresql_nulls_not_distinct=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('reimb_dte_clusters',
    sa.Column('cluster', sa.String(), nullable=False),
    sa.Column('daily_rate', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.BigInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['core_users.id'], name=op.f('fk_reimb_dte_clusters_created_by_core_users')),
    sa.ForeignKeyConstraint(['deleted_by'], ['core_users.id'], name=op.f('fk_reimb_dte_clusters_deleted_by_core_users')),
    sa.ForeignKeyConstraint(['updated_by'], ['core_users.id'], name=op.f('fk_reimb_dte_clusters_updated_by_core_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reimb_dte_clusters'))
    )
    op.create_index('uq_reimb_dte_clusters_cluster_eff', 'reimb_dte_clusters', ['cluster', 'effective_from'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('reimb_region_clusters',
    sa.Column('region_code', sa.String(), nullable=False),
    sa.Column('region_name', sa.String(), nullable=True),
    sa.Column('cluster', sa.String(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.BigInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['core_users.id'], name=op.f('fk_reimb_region_clusters_created_by_core_users')),
    sa.ForeignKeyConstraint(['deleted_by'], ['core_users.id'], name=op.f('fk_reimb_region_clusters_deleted_by_core_users')),
    sa.ForeignKeyConstraint(['updated_by'], ['core_users.id'], name=op.f('fk_reimb_region_clusters_updated_by_core_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reimb_region_clusters'))
    )
    op.create_index('ix_reimb_region_clusters_cluster', 'reimb_region_clusters', ['cluster'], unique=False)
    op.create_index('uq_reimb_region_clusters_region_eff', 'reimb_region_clusters', ['region_code', 'effective_from'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('reimb_return_reason_catalogs',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('category', sa.Enum('missing_doc', 'wrong_amount', 'wrong_form', 'no_signature', 'late', 'policy', 'other', name='reimb_return_reason_category'), nullable=False),
    sa.Column('promoted_check', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.BigInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['core_users.id'], name=op.f('fk_reimb_return_reason_catalogs_created_by_core_users')),
    sa.ForeignKeyConstraint(['deleted_by'], ['core_users.id'], name=op.f('fk_reimb_return_reason_catalogs_deleted_by_core_users')),
    sa.ForeignKeyConstraint(['updated_by'], ['core_users.id'], name=op.f('fk_reimb_return_reason_catalogs_updated_by_core_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reimb_return_reason_catalogs'))
    )
    op.create_index('uq_reimb_return_reason_catalogs_code', 'reimb_return_reason_catalogs', ['code'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('reimb_claims',
    sa.Column('ref_no', sa.String(), nullable=True),
    sa.Column('kind', sa.Enum('reimbursement', 'liquidation', name='reimb_claim_kind'), nullable=False),
    sa.Column('claimant_id', sa.BigInteger(), nullable=False),
    sa.Column('activity_id', sa.BigInteger(), nullable=True),
    sa.Column('workflow_instance_id', sa.BigInteger(), nullable=True),
    sa.Column('dpo_no', sa.String(), nullable=True),
    sa.Column('dpo_date', sa.Date(), nullable=True),
    sa.Column('dpo_document_id', sa.BigInteger(), nullable=True),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('destination', sa.Text(), nullable=True),
    sa.Column('destination_region_code', sa.String(), nullable=True),
    sa.Column('date_depart', sa.Date(), nullable=True),
    sa.Column('date_return', sa.Date(), nullable=True),
    sa.Column('fund_source', sa.Enum('GF_ORS', 'TF_BUR', name='reimb_fund_source'), nullable=True),
    sa.Column('is_jo_cos', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('cash_advance_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('holder_kind', sa.Enum('user', 'external_fms', name='reimb_holder_kind'), nullable=True),
    sa.Column('holder_id', sa.BigInteger(), nullable=True),
    sa.Column('holder_since', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('next_action', sa.Text(), nullable=True),
    sa.Column('liquidation_deadline', sa.Date(), nullable=True),
    sa.Column('totals', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('custom', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['core_activities.id'], name=op.f('fk_reimb_claims_activity_id_core_activities')),
    sa.ForeignKeyConstraint(['cash_advance_id'], ['reimb_cash_advances.id'], name=op.f('fk_reimb_claims_cash_advance_id_reimb_cash_advances')),
    sa.ForeignKeyConstraint(['claimant_id'], ['core_staff.id'], name=op.f('fk_reimb_claims_claimant_id_core_staff')),
    sa.ForeignKeyConstraint(['created_by'], ['core_users.id'], name=op.f('fk_reimb_claims_created_by_core_users')),
    sa.ForeignKeyConstraint(['deleted_by'], ['core_users.id'], name=op.f('fk_reimb_claims_deleted_by_core_users')),
    sa.ForeignKeyConstraint(['updated_by'], ['core_users.id'], name=op.f('fk_reimb_claims_updated_by_core_users')),
    sa.ForeignKeyConstraint(['workflow_instance_id'], ['core_workflow_instances.id'], name=op.f('fk_reimb_claims_workflow_instance_id_core_workflow_instances')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reimb_claims'))
    )
    op.create_index('ix_reimb_claims_activity_id', 'reimb_claims', ['activity_id'], unique=False)
    op.create_index('ix_reimb_claims_cash_advance_id', 'reimb_claims', ['cash_advance_id'], unique=False)
    op.create_index('ix_reimb_claims_claimant_id', 'reimb_claims', ['claimant_id'], unique=False)
    op.create_index('ix_reimb_claims_kind', 'reimb_claims', ['kind'], unique=False)
    op.create_index('ix_reimb_claims_status', 'reimb_claims', ['status'], unique=False)
    op.create_index('ix_reimb_claims_workflow_instance_id', 'reimb_claims', ['workflow_instance_id'], unique=False)
    op.create_index('uq_reimb_claims_ref_no', 'reimb_claims', ['ref_no'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('reimb_checklist_items',
    sa.Column('claim_id', sa.BigInteger(), nullable=False),
    sa.Column('catalog_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('missing', 'attached', 'generated', 'auto_passed', 'auto_flagged', 'waived', name='reimb_checklist_item_status'), server_default='missing', nullable=False),
    sa.Column('attachment_ids', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('waiver_reason', sa.Text(), nullable=True),
    sa.Column('checked_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('checked_by', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['catalog_id'], ['reimb_checklist_catalogs.id'], name=op.f('fk_reimb_checklist_items_catalog_id_reimb_checklist_catalogs')),
    sa.ForeignKeyConstraint(['checked_by'], ['core_users.id'], name=op.f('fk_reimb_checklist_items_checked_by_core_users')),
    sa.ForeignKeyConstraint(['claim_id'], ['reimb_claims.id'], name=op.f('fk_reimb_checklist_items_claim_id_reimb_claims')),
    sa.ForeignKeyConstraint(['created_by'], ['core_users.id'], name=op.f('fk_reimb_checklist_items_created_by_core_users')),
    sa.ForeignKeyConstraint(['deleted_by'], ['core_users.id'], name=op.f('fk_reimb_checklist_items_deleted_by_core_users')),
    sa.ForeignKeyConstraint(['updated_by'], ['core_users.id'], name=op.f('fk_reimb_checklist_items_updated_by_core_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reimb_checklist_items'))
    )
    op.create_index('ix_reimb_checklist_items_catalog_id', 'reimb_checklist_items', ['catalog_id'], unique=False)
    op.create_index('ix_reimb_checklist_items_claim_id', 'reimb_checklist_items', ['claim_id'], unique=False)
    op.create_table('reimb_external_events',
    sa.Column('claim_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('noted_by', sa.String(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['reimb_claims.id'], name=op.f('fk_reimb_external_events_claim_id_reimb_claims')),
    sa.ForeignKeyConstraint(['created_by'], ['core_users.id'], name=op.f('fk_reimb_external_events_created_by_core_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reimb_external_events'))
    )
    op.create_index('ix_reimb_external_events_claim_id', 'reimb_external_events', ['claim_id'], unique=False)
    op.create_table('reimb_itinerary_legs',
    sa.Column('claim_id', sa.BigInteger(), nullable=False),
    sa.Column('seq', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('leg_date', sa.Date(), nullable=True),
    sa.Column('place', sa.Text(), nullable=True),
    sa.Column('destination_region_code', sa.String(), nullable=True),
    sa.Column('time_depart', sa.String(), nullable=True),
    sa.Column('time_arrive', sa.String(), nullable=True),
    sa.Column('transport_mode', sa.Enum('plane', 'bus', 'boat', 'taxi', 'ride_hail', 'gov_vehicle', 'other', name='reimb_transport_mode'), nullable=True),
    sa.Column('fare', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('per_diem_pct', sa.Integer(), nullable=True),
    sa.Column('per_diem_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('leg_total', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('lodging_provided', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('meals_provided', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['claim_id'], ['reimb_claims.id'], name=op.f('fk_reimb_itinerary_legs_claim_id_reimb_claims')),
    sa.ForeignKeyConstraint(['created_by'], ['core_users.id'], name=op.f('fk_reimb_itinerary_legs_created_by_core_users')),
    sa.ForeignKeyConstraint(['deleted_by'], ['core_users.id'], name=op.f('fk_reimb_itinerary_legs_deleted_by_core_users')),
    sa.ForeignKeyConstraint(['updated_by'], ['core_users.id'], name=op.f('fk_reimb_itinerary_legs_updated_by_core_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reimb_itinerary_legs'))
    )
    op.create_index('ix_reimb_itinerary_legs_claim_id', 'reimb_itinerary_legs', ['claim_id'], unique=False)
    op.create_table('reimb_return_events',
    sa.Column('claim_id', sa.BigInteger(), nullable=False),
    sa.Column('step_id', sa.BigInteger(), nullable=True),
    sa.Column('reason_ids', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('free_comment', sa.Text(), nullable=True),
    sa.Column('returned_to', sa.Enum('claimant', 'previous_step', name='reimb_return_target'), server_default='claimant', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['reimb_claims.id'], name=op.f('fk_reimb_return_events_claim_id_reimb_claims')),
    sa.ForeignKeyConstraint(['created_by'], ['core_users.id'], name=op.f('fk_reimb_return_events_created_by_core_users')),
    sa.ForeignKeyConstraint(['step_id'], ['core_workflow_steps.id'], name=op.f('fk_reimb_return_events_step_id_core_workflow_steps')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reimb_return_events'))
    )
    op.create_index('ix_reimb_return_events_claim_id', 'reimb_return_events', ['claim_id'], unique=False)
    op.create_index('ix_reimb_return_events_step_id', 'reimb_return_events', ['step_id'], unique=False)
    op.create_table('reimb_status_histories',
    sa.Column('claim_id', sa.BigInteger(), nullable=False),
    sa.Column('from_status', sa.String(), nullable=True),
    sa.Column('to_status', sa.String(), nullable=False),
    sa.Column('actor_id', sa.BigInteger(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['core_users.id'], name=op.f('fk_reimb_status_histories_actor_id_core_users')),
    sa.ForeignKeyConstraint(['claim_id'], ['reimb_claims.id'], name=op.f('fk_reimb_status_histories_claim_id_reimb_claims')),
    sa.ForeignKeyConstraint(['created_by'], ['core_users.id'], name=op.f('fk_reimb_status_histories_created_by_core_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reimb_status_histories'))
    )
    op.create_index('ix_reimb_status_histories_claim_id', 'reimb_status_histories', ['claim_id'], unique=False)
    op.create_table('reimb_attachments',
    sa.Column('claim_id', sa.BigInteger(), nullable=False),
    sa.Column('attachment_id', sa.BigInteger(), nullable=False),
    sa.Column('checklist_item_id', sa.BigInteger(), nullable=True),
    sa.Column('custody', sa.Enum('scanned', 'with_accounting', 'forwarded_coa', name='reimb_attachment_custody'), server_default='scanned', nullable=False),
    sa.Column('retention_class', sa.String(), server_default='financial_10yr', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['attachment_id'], ['core_attachments.id'], name=op.f('fk_reimb_attachments_attachment_id_core_attachments')),
    sa.ForeignKeyConstraint(['checklist_item_id'], ['reimb_checklist_items.id'], name=op.f('fk_reimb_attachments_checklist_item_id_reimb_checklist_items')),
    sa.ForeignKeyConstraint(['claim_id'], ['reimb_claims.id'], name=op.f('fk_reimb_attachments_claim_id_reimb_claims')),
    sa.ForeignKeyConstraint(['created_by'], ['core_users.id'], name=op.f('fk_reimb_attachments_created_by_core_users')),
    sa.ForeignKeyConstraint(['deleted_by'], ['core_users.id'], name=op.f('fk_reimb_attachments_deleted_by_core_users')),
    sa.ForeignKeyConstraint(['updated_by'], ['core_users.id'], name=op.f('fk_reimb_attachments_updated_by_core_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reimb_attachments'))
    )
    op.create_index('ix_reimb_attachments_attachment_id', 'reimb_attachments', ['attachment_id'], unique=False)
    op.create_index('ix_reimb_attachments_checklist_item_id', 'reimb_attachments', ['checklist_item_id'], unique=False)
    op.create_index('ix_reimb_attachments_claim_id', 'reimb_attachments', ['claim_id'], unique=False)
    # ### end Alembic commands ###

    # Append-only tables: the runtime role may INSERT + SELECT but never UPDATE
    # (immutability by grant — database-standards §6/§8). These are audited (module
    # tables cannot be added to core/audit.py::_UNAUDITED without core→module imports).
    for table in (
        "reimb_return_events",
        "reimb_status_histories",
        "reimb_external_events",
    ):
        op.execute(f"REVOKE UPDATE ON {table} FROM oc_app")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_reimb_attachments_claim_id', table_name='reimb_attachments')
    op.drop_index('ix_reimb_attachments_checklist_item_id', table_name='reimb_attachments')
    op.drop_index('ix_reimb_attachments_attachment_id', table_name='reimb_attachments')
    op.drop_table('reimb_attachments')
    op.drop_index('ix_reimb_status_histories_claim_id', table_name='reimb_status_histories')
    op.drop_table('reimb_status_histories')
    op.drop_index('ix_reimb_return_events_step_id', table_name='reimb_return_events')
    op.drop_index('ix_reimb_return_events_claim_id', table_name='reimb_return_events')
    op.drop_table('reimb_return_events')
    op.drop_index('ix_reimb_itinerary_legs_claim_id', table_name='reimb_itinerary_legs')
    op.drop_table('reimb_itinerary_legs')
    op.drop_index('ix_reimb_external_events_claim_id', table_name='reimb_external_events')
    op.drop_table('reimb_external_events')
    op.drop_index('ix_reimb_checklist_items_claim_id', table_name='reimb_checklist_items')
    op.drop_index('ix_reimb_checklist_items_catalog_id', table_name='reimb_checklist_items')
    op.drop_table('reimb_checklist_items')
    op.drop_index('uq_reimb_claims_ref_no', table_name='reimb_claims', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_reimb_claims_workflow_instance_id', table_name='reimb_claims')
    op.drop_index('ix_reimb_claims_status', table_name='reimb_claims')
    op.drop_index('ix_reimb_claims_kind', table_name='reimb_claims')
    op.drop_index('ix_reimb_claims_claimant_id', table_name='reimb_claims')
    op.drop_index('ix_reimb_claims_cash_advance_id', table_name='reimb_claims')
    op.drop_index('ix_reimb_claims_activity_id', table_name='reimb_claims')
    op.drop_table('reimb_claims')
    op.drop_index('uq_reimb_return_reason_catalogs_code', table_name='reimb_return_reason_catalogs', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('reimb_return_reason_catalogs')
    op.drop_index('uq_reimb_region_clusters_region_eff', table_name='reimb_region_clusters', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_reimb_region_clusters_cluster', table_name='reimb_region_clusters')
    op.drop_table('reimb_region_clusters')
    op.drop_index('uq_reimb_dte_clusters_cluster_eff', table_name='reimb_dte_clusters', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('reimb_dte_clusters')
    op.drop_index('uq_reimb_configs_key_scope', table_name='reimb_configs', postgresql_nulls_not_distinct=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_reimb_configs_key', table_name='reimb_configs')
    op.drop_table('reimb_configs')
    op.drop_index('uq_reimb_checklist_catalogs_kind_code', table_name='reimb_checklist_catalogs', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_reimb_checklist_catalogs_group', table_name='reimb_checklist_catalogs')
    op.drop_table('reimb_checklist_catalogs')
    op.drop_index('uq_reimb_cash_advances_open_per_claimant', table_name='reimb_cash_advances', postgresql_where=sa.text("status IN ('open', 'liquidation_started', 'overdue') AND deleted_at IS NULL"))
    op.drop_index('ix_reimb_cash_advances_status', table_name='reimb_cash_advances')
    op.drop_index('ix_reimb_cash_advances_date_return', table_name='reimb_cash_advances')
    op.drop_index('ix_reimb_cash_advances_claimant_id', table_name='reimb_cash_advances')
    op.drop_table('reimb_cash_advances')
    op.drop_index('uq_core_reference_sequences_scope_year', table_name='core_reference_sequences')
    op.drop_table('core_reference_sequences')
    # ### end Alembic commands ###

    # Drop the native enum TYPES the tables above created (autogenerate omits this,
    # which would break a down→up cycle with "type already exists").
    bind = op.get_bind()
    for enum_name in _REIMB_ENUMS:
        postgresql.ENUM(name=enum_name).drop(bind, checkfirst=True)
