"""document generation — attachment provenance, frozen snapshots, template map

Revision ID: 0018
Revises: 0017
Create Date: 2026-08-03

Stage C Increment R-5-gen (template auto-assembly). Lands core-service #8
(template → PDF) and the snapshot half of core-service #3, plus the module table
R-1 deferred here. Three changes:

1. **``core_attachments.origin``** (new enum ``core_attachment_origin``,
   ``uploaded`` | ``generated``, default ``uploaded``) — provenance, and the
   single column three otherwise-separate flags collapse into:
     a. SCAN. Generated bytes are rendered in-process from autoescaped templates
        and never leave it, so they are born ``clean``. Leaving them ``pending``
        would be actively harmful: in production ``NullScanner`` returns
        ``error``, so any tenant without ClamAV could never download a document
        the system generated for them — a missing optional dependency turned
        into a permanently broken packet by the fail-closed download gate.
     b. DISPOSITION. Only generated PDFs may be served ``inline`` for preview
        (§9.3 step 4 promises previewable cards, and a browser will not preview
        a ``Content-Disposition: attachment`` response). Uploaded PDFs stay
        ``attachment`` forever — they can embed JavaScript, and rendering a
        claimant's upload inline in the app's own origin is stored XSS.
     c. COUNTING. ``evidence_counts`` filters on ``uploaded`` so a generated
        document is never tallied as evidence a human supplied.
   Backfill is the default: every existing row IS an upload (nothing generated
   anything before this migration).

2. **``core_document_snapshots``** (+ enum ``core_document_snapshot_status``) —
   core-service #3. Signatures bind to a frozen PDF, never to live data, or
   re-rendering silently changes the document someone already signed. Two hashes
   because they answer different questions: ``content_sha256`` over the bytes
   (tamper evidence) and ``source_fingerprint`` over the canonical render
   context (change detection — PDF bytes embed a creation timestamp, so
   identical data renders to different bytes and hashing output could never
   detect an edit). ``superseded`` and ``voided`` are kept distinct: the first is
   an ordinary reissue, the second records that a document was invalidated
   because its inputs moved — which is precisely the fact an auditor is looking
   for.

3. **``reimb_template_maps``** — deferred from R-1 to R-5 by ``0013``. Ships as a
   *binding* table (checklist code → registered document key), not the spec's
   placeholder-merge map: under Jinja the template IS the field mapping, so a
   JSONB placeholder dictionary would be a second grammar to validate for no
   gain. What remains genuinely configurable — which form satisfies which
   requirement, under which circular — is what the R-9 catalog editor needs.

No explicit GRANTs: ``0001``'s ``ALTER DEFAULT PRIVILEGES`` already grants
SELECT/INSERT/UPDATE on new tables to ``oc_app``. None of these are append-only,
so no ``REVOKE UPDATE`` either — snapshots legitimately transition
active → superseded/voided.

Reversible (down→up) + idempotent.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "0018"
down_revision: Union[str, None] = "0017"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Native enums created EXPLICITLY below (not inline by add_column/create_table)
# so that downgrade can drop the TYPEs — autogenerate omits both halves.
#
# ``create_type=False`` is load-bearing: without it SQLAlchemy emits its own
# CREATE TYPE when the type is first used in a DDL statement, which collides
# with the explicit ``.create()`` and fails the whole migration with
# DuplicateObjectError. Declaring the types once and telling the column
# definitions not to re-declare them is the only combination that is both
# idempotent on upgrade and reversible on downgrade.
_ORIGIN = postgresql.ENUM(
    "uploaded", "generated", name="core_attachment_origin", create_type=False
)
_SNAPSHOT_STATUS = postgresql.ENUM(
    "active",
    "superseded",
    "voided",
    name="core_document_snapshot_status",
    create_type=False,
)


def upgrade() -> None:
    bind = op.get_bind()
    # checkfirst: a re-run after a partial failure must not trip over its own
    # first attempt.
    postgresql.ENUM(
        "uploaded", "generated", name="core_attachment_origin"
    ).create(bind, checkfirst=True)
    postgresql.ENUM(
        "active", "superseded", "voided", name="core_document_snapshot_status"
    ).create(bind, checkfirst=True)

    # 1. Attachment provenance. NOT NULL with a default is safe on a populated
    # table: every pre-existing row is, by definition, an upload.
    op.add_column(
        "core_attachments",
        sa.Column(
            "origin",
            _ORIGIN,
            nullable=False,
            server_default="uploaded",
        ),
    )

    # 2. Frozen snapshots (core-service #3).
    op.create_table(
        "core_document_snapshots",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("subject_kind", sa.String(), nullable=False),
        sa.Column("subject_id", sa.BigInteger(), nullable=False),
        sa.Column("document_key", sa.String(), nullable=False),
        sa.Column("attachment_id", sa.BigInteger(), nullable=False),
        sa.Column("content_sha256", sa.String(), nullable=False),
        sa.Column("source_fingerprint", sa.String(), nullable=False),
        sa.Column("revision_no", sa.Integer(), nullable=True),
        sa.Column(
            "is_draft", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "status", _SNAPSHOT_STATUS, server_default="active", nullable=False
        ),
        sa.Column("voided_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("voided_by", sa.BigInteger(), nullable=True),
        sa.Column("void_reason", sa.Text(), nullable=True),
        sa.Column("generated_by", sa.BigInteger(), nullable=True),
        sa.Column("generated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.BigInteger(), nullable=True),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_by", sa.BigInteger(), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ["attachment_id"],
            ["core_attachments.id"],
            name=op.f("fk_core_document_snapshots_attachment_id_core_attachments"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["core_users.id"],
            name=op.f("fk_core_document_snapshots_created_by_core_users"),
        ),
        sa.ForeignKeyConstraint(
            ["deleted_by"],
            ["core_users.id"],
            name=op.f("fk_core_document_snapshots_deleted_by_core_users"),
        ),
        sa.ForeignKeyConstraint(
            ["generated_by"],
            ["core_users.id"],
            name=op.f("fk_core_document_snapshots_generated_by_core_users"),
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["core_users.id"],
            name=op.f("fk_core_document_snapshots_updated_by_core_users"),
        ),
        sa.ForeignKeyConstraint(
            ["voided_by"],
            ["core_users.id"],
            name=op.f("fk_core_document_snapshots_voided_by_core_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_core_document_snapshots")),
    )
    op.create_index(
        "ix_core_document_snapshots_subject",
        "core_document_snapshots",
        ["subject_kind", "subject_id"],
        unique=False,
    )
    op.create_index(
        "ix_core_document_snapshots_attachment_id",
        "core_document_snapshots",
        ["attachment_id"],
        unique=False,
    )
    # The lookup every read performs: "the live official copy of this document".
    # Not unique — supersession is a two-step (mark old, insert new) inside one
    # transaction, and a unique index would make the ordinary reissue path race
    # against itself.
    op.create_index(
        "ix_core_document_snapshots_active",
        "core_document_snapshots",
        ["subject_kind", "subject_id", "document_key"],
        unique=False,
        postgresql_where=sa.text("status = 'active' AND deleted_at IS NULL"),
    )

    # 3. Template bindings (module-side; core-service #13 candidate).
    op.create_table(
        "reimb_template_maps",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("claim_kind", sa.String(), nullable=True),
        sa.Column("checklist_code", sa.String(), nullable=False),
        sa.Column("document_key", sa.String(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("form_no", sa.Text(), nullable=True),
        sa.Column("circular_version", sa.String(), nullable=True),
        sa.Column("sort", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.BigInteger(), nullable=True),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_by", sa.BigInteger(), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["core_users.id"],
            name=op.f("fk_reimb_template_maps_created_by_core_users"),
        ),
        sa.ForeignKeyConstraint(
            ["deleted_by"],
            ["core_users.id"],
            name=op.f("fk_reimb_template_maps_deleted_by_core_users"),
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["core_users.id"],
            name=op.f("fk_reimb_template_maps_updated_by_core_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reimb_template_maps")),
    )
    op.create_index(
        "uq_reimb_template_maps_kind_code",
        "reimb_template_maps",
        ["claim_kind", "checklist_code"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )


def downgrade() -> None:
    op.drop_index(
        "uq_reimb_template_maps_kind_code", table_name="reimb_template_maps"
    )
    op.drop_table("reimb_template_maps")

    op.drop_index(
        "ix_core_document_snapshots_active", table_name="core_document_snapshots"
    )
    op.drop_index(
        "ix_core_document_snapshots_attachment_id",
        table_name="core_document_snapshots",
    )
    op.drop_index(
        "ix_core_document_snapshots_subject", table_name="core_document_snapshots"
    )
    op.drop_table("core_document_snapshots")

    op.drop_column("core_attachments", "origin")

    bind = op.get_bind()
    postgresql.ENUM(
        "active", "superseded", "voided", name="core_document_snapshot_status"
    ).drop(bind, checkfirst=True)
    postgresql.ENUM(
        "uploaded", "generated", name="core_attachment_origin"
    ).drop(bind, checkfirst=True)
