"""Shared declarative Base, naming convention, and mandatory-column mixins.

Implements docs/standards/database-standards.md:
- §2  table names: <module_prefix>_<plural_snake_case>
- §3  PK = BIGINT identity ``id``; FK column = <singular_referenced>_id.
      Every ``*_by`` column is a future FK to ``core_users.id`` — plain
      nullable BIGINT until the Phase 2 migration adds the constraints.
- §4  deterministic constraint/index names (Alembic autogenerate consumes this)
- §6  mandatory columns by table class (business / lookup / append-only)
"""

from datetime import datetime

from sqlalchemy import BigInteger, Identity, MetaData, true
from sqlalchemy.dialects.postgresql import TIMESTAMP
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column
from sqlalchemy.sql import func

from office_connect.core.time import utc_now

NAMING_CONVENTION = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    metadata = MetaData(naming_convention=NAMING_CONVENTION)


class PKMixin:
    """``id BIGINT GENERATED BY DEFAULT AS IDENTITY`` (§3).

    Append-only hash-chained tables define their own PK with
    ``Identity(always=True)`` instead — nobody may supply an explicit id
    into the chain.
    """

    id: Mapped[int] = mapped_column(BigInteger, Identity(), primary_key=True)


class AuditColsMixin:
    """Mandatory ownership columns for business + lookup tables (§6, rule 5).

    ``updated_at``'s ``onupdate`` fires on ORM updates only — deliberate,
    consistent with app-level auditing (raw-SQL writes are out of contract).
    """

    created_at: Mapped[datetime] = mapped_column(
        TIMESTAMP(timezone=True), nullable=False, server_default=func.now()
    )
    created_by: Mapped[int | None] = mapped_column(BigInteger)  # future FK core_users.id
    updated_at: Mapped[datetime] = mapped_column(
        TIMESTAMP(timezone=True),
        nullable=False,
        server_default=func.now(),
        onupdate=utc_now,
    )
    updated_by: Mapped[int | None] = mapped_column(BigInteger)  # future FK core_users.id


class SoftDeleteMixin:
    """Soft-delete columns (§8, rule 6). ``deleted_at IS NULL`` = live row.

    The global filter in ``core/soft_delete.py`` keys off this mixin; never
    set these columns directly — use ``soft_delete()``.
    """

    deleted_at: Mapped[datetime | None] = mapped_column(TIMESTAMP(timezone=True))
    deleted_by: Mapped[int | None] = mapped_column(BigInteger)  # future FK core_users.id


class LookupMixin:
    """Lookup/catalog tables: deactivate (``is_active=false``), never delete (§6)."""

    is_active: Mapped[bool] = mapped_column(nullable=False, server_default=true())
